name: "CI-Build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 3
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0', '8.1', '8.2', '8.3']
    steps:
    - uses: actions/checkout@master

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: xdebug, mbstring, intl, iconv

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install phive
      run: wget -O phive.phar https://phar.io/releases/phive.phar

    - name: Make phive executable
      run: chmod +x ./phive.phar

    - name: Install tooling
      run: GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} ./phive.phar --no-progress --home ./.phive install --force-accept-unsigned --trust-gpg-keys 51C67305FFC2E5C0,4AA394086372C20A,31C7E470E2138192,8E730BA25823D8B5,CF1A108D0E7AE720

    - name: Execute unit tests
      run: tools/phpunit

    - name: Check coding style
      run: tools/phpcs --standard=psr12 src tests

    - name: Static code analysis
      run: tools/phpstan analyse
